### ISSUE TITLE
WIP : L5 passwords.sent

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel4-lang#311]
From : "sent" => "Password reminder sent!"
To : "sent" => "Password reset link sent!"

Just in `laravel5` branch.

Status :

- [ ] Albanian
- [ ] Arabic
- [ ] Brazilian
- [ ] Bosnian
- [ ] Bulgarian
- [ ] Cambodian
- [ ] Catalan
- [x] Chinese
- [x] Chinese from Taiwan (zh-TW)
- [ ] Czech
- [ ] Danish
- [ ] Dutch
- [ ] Finnish
- [x] French
- [ ] German
- [ ] Greek
- [ ] Hebrew
- [ ] Hungarian
- [ ] Indonesian
- [ ] Italian
- [ ] Japanese
- [ ] Korean
- [x] Lithunian
- [ ] Macedonian
- [ ] Montenegrin
- [ ] Norwegian Bokmål
- [ ] Polish
- [ ] Portuguese
- [ ] Romanian
- [x] Russian
- [ ] Serbian
- [ ] Slovak
- [ ] Spanish
- [ ] Swedish
- [ ] Thai
- [x] Traditional Chinese (Hong Kong)
- [ ] Turkish
- [ ] Vietnamese

**Comment by idhamperdameian** [comment]
This issue may not relevan with https://github.com/laravel/laravel/commit/359af29ef3fd67b12029fa2a4b0455a9bf4731c2#diff-75

**Comment by caouecs** [comment]
Hello @idhamperdameian,
yes, but I don't know if it's a try or not...

**Comment by idhamperdameian** [comment]
So we just wait right?

2015-01-17 16:52 GMT+07.00, Fred Delrieu <notifications@github.com>:
> Hello @idhamperdameian,
> yes, but I don't know if it's a try or not...
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/caouecs/Laravel4-lang/issues/311#issuecomment-70361166


-- 
Yeshua ha-Mashiach Memberkati!

**Comment by caouecs** [comment]
We wait the end of week, to be sure

**Comment by caouecs** [comment]
Close for https://github.com/caouecs/Laravel4-lang/issues/323
